### ISSUE TITLE
[TODO] - Write-up

### ISSUE THREAD

**Issue by Belchy06** [Belchy06/Thesis#3]
- [ ] Drop requirement for low complexity
- [ ] Expand on low latency ability by removing need for jitter buffer
- [ ] Add lit review for Scalable Video Coding as an error resilience technique
- [ ] Add lit review for Interleaving as an error resilience technique
